### ISSUE TITLE
Fall damages almost never work

### ISSUE THREAD

**Issue by oskarkk** [MrMicky-FR/InfiniteJump#7]
With `RemoveFallDamages: false` I almost never get fall damages. I'm getting them in some rare cases, I think when I'm bumping into the walls and then falling or something. I'm using the newest Spigot and InfiniteJump.

**Comment by NatsumeLS** [comment]
This is also an issue here
For me players always never get fall damage if they only jump once. But if they do another jump midair they get fall damage normally.

**Comment by KleinDevDE** [comment]
Players get fall damage even though `RemoveFallDamages: false` is set?
Or do players generally not get any fall damage anymore, i.e. not even when they fall off the cliff?

Is this issue still present?
If yes, please provide some more informations like:
- A list of running plugins on your server
- Your server version
- Plugin version
- Your config file

**Comment by WongIong** [comment]
When player triggered their jump, the fall damage will be counted.
But if they didn't trigger it, they won't get damage.

I think this is because the flight mode is always on when they were available to jump. So that minecraft will not calculate their fall damage.
Maybe you will have to calculate it inside the plugin and then give the damage to player.

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
